<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('products')->delete();
        
        \DB::table('products')->insert(array (
            0 => 
            array (
                'id' => 1,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'nqdajOY8MIMW0uKSxpxGZ8nkacQIEq3v5c9C8tdX.webp',
                'slug' => 'iphone-16-pro',
                'title' => 'iPhone 16 Pro',
                'description' => 'White, 128GB',
                'price' => '2199.98',
                'created_at' => '2025-07-25 12:41:59',
                'updated_at' => '2025-07-25 12:46:30',
                'deleted_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'eNoHyXsjU3xHDnUWLHYSQYHcdHHanisXG38wNbr5.webp',
                'slug' => 'iphone-16e',
                'title' => 'iPhone 16e',
                'description' => 'White, 128GB',
                'price' => '1269.00',
                'created_at' => '2025-07-25 12:47:34',
                'updated_at' => '2025-07-25 12:47:34',
                'deleted_at' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'AtKBeJ5mtJi0z7itf6kc2sRPscgx3SfGIfX4LbNC.webp',
                'slug' => 'iphone-16',
                'title' => 'iPhone 16',
                'description' => 'Ultramarine, 128GB',
                'price' => '1699.00',
                'created_at' => '2025-07-25 12:49:16',
                'updated_at' => '2025-07-25 12:49:16',
                'deleted_at' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'HLqeGRhgaFeqAZjC9h01khgyoLFbebsoW8bVIMsv.webp',
                'slug' => 'iphone-15-pro-max',
                'title' => 'iPhone 15 Pro Max',
                'description' => 'Black Titanium, 512GB',
                'price' => '2749.00',
                'created_at' => '2025-07-25 12:50:13',
                'updated_at' => '2025-07-25 12:50:13',
                'deleted_at' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'nDmB1dR1yKEYUVbW5g4kJLZAxMo00zWt6Pa3HiIF.webp',
                'slug' => 'iphone-16-pro-max',
                'title' => 'iPhone 16 Pro Max',
                'description' => 'Natural Titanium, 256GB',
                'price' => '2749.00',
                'created_at' => '2025-07-25 12:52:06',
                'updated_at' => '2025-07-25 12:52:06',
                'deleted_at' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'UGvdXNngovsHrxwpNiNwcNn1H4oKcXAo4XVEFVn5.webp',
                'slug' => 'iphone-15',
                'title' => 'iPhone 15',
                'description' => 'Pink, 128GB',
                'price' => '1499.00',
                'created_at' => '2025-07-25 12:54:21',
                'updated_at' => '2025-07-25 14:13:09',
                'deleted_at' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'aC5iTXSVZnPaWEsaHwXXJ7hJ4txSiRdbTSmQTKgF.webp',
                'slug' => 'iphone-15-plus',
                'title' => 'iPhone 15 Plus',
                'description' => 'Yellow, 128GB',
                'price' => '1739.00',
                'created_at' => '2025-07-25 12:55:21',
                'updated_at' => '2025-07-25 12:55:21',
                'deleted_at' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'IZEWgbKxupoAN6IKZYJHoTtL7xT0uddElKL9wnbf.webp',
                'slug' => 'iphone-14',
                'title' => 'iPhone 14',
                'description' => 'Purple, 128GB',
                'price' => '1299.00',
                'created_at' => '2025-07-25 12:56:22',
                'updated_at' => '2025-07-25 14:13:00',
                'deleted_at' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'uIWTE3jijzVnes97CK8Z81TyCzJN2ryqzdtQoz1w.webp',
                'slug' => 'iphone-14-pro-max',
                'title' => 'iPhone 14 Pro Max',
                'description' => 'Deep Purple, 256GB',
                'price' => '2599.00',
                'created_at' => '2025-07-25 12:57:13',
                'updated_at' => '2025-07-25 12:57:13',
                'deleted_at' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 's3XE2Tsj7Gpdo43HNUyzE7FOyDCWKyH8mCltkMNJ.webp',
                'slug' => 'iphone-13',
                'title' => 'iPhone 13',
                'description' => 'Midnight, 128GB',
                'price' => '1049.99',
                'created_at' => '2025-07-25 12:58:20',
                'updated_at' => '2025-07-25 12:58:20',
                'deleted_at' => NULL,
            ),
            10 => 
            array (
                'id' => 11,
                'creator_id' => 1,
                'category_id' => 1,
                'image' => 'asIPkddhpona2bpygLgXlA7CIAqTeZh1M0OZHqkM.webp',
                'slug' => 'iphone-12',
                'title' => 'iPhone 12',
                'description' => 'Black, 64GB',
                'price' => '839.99',
                'created_at' => '2025-07-25 12:59:37',
                'updated_at' => '2025-07-25 12:59:37',
                'deleted_at' => NULL,
            ),
            11 => 
            array (
                'id' => 12,
                'creator_id' => 1,
                'category_id' => 2,
                'image' => '15AsUsn8xBZnB69rXQPjBDxaMZ3VYNnzAH8jmKuR.webp',
                'slug' => 'macbook-air-15-inch-m4-chip',
            'title' => 'MacBook Air (15-inch) M4 chip',
                'description' => 'Midnight, 16GB, 256GB',
                'price' => '2959.00',
                'created_at' => '2025-07-25 13:02:37',
                'updated_at' => '2025-07-25 13:02:37',
                'deleted_at' => NULL,
            ),
            12 => 
            array (
                'id' => 13,
                'creator_id' => 1,
                'category_id' => 2,
                'image' => 'juG1zwJHtezzu5qzuWUoioasEFd9kgeDsQ13zUfK.webp',
                'slug' => 'macbook-air-13-inch-m4-chip',
            'title' => 'MacBook Air (13-inch) M4 chip',
                'description' => 'Midnight, 16GB, 256GB',
                'price' => '2389.99',
                'created_at' => '2025-07-25 13:03:42',
                'updated_at' => '2025-07-25 13:03:42',
                'deleted_at' => NULL,
            ),
            13 => 
            array (
                'id' => 14,
                'creator_id' => 1,
                'category_id' => 2,
                'image' => 'Pk1WoXb4fY7qZXoLiZ4PKQ9dzLKqUYiG2bXwaIOn.webp',
                'slug' => 'macbook-air-15-inch-m3-chip',
            'title' => 'MacBook Air (15-inch) M3 chip',
                'description' => 'Starlight, 8GB, 256GB',
                'price' => '2399.00',
                'created_at' => '2025-07-25 13:04:47',
                'updated_at' => '2025-07-25 13:04:47',
                'deleted_at' => NULL,
            ),
            14 => 
            array (
                'id' => 15,
                'creator_id' => 1,
                'category_id' => 2,
                'image' => 'raLy3femYw455vxSdi5AAqLchRnTEluwzQrWoxar.webp',
                'slug' => 'macbook-air-13-inch-m3-chip',
            'title' => 'MacBook Air (13-inch) M3 chip',
                'description' => 'Space Grey, 24GB, 512GB',
                'price' => '3099.00',
                'created_at' => '2025-07-25 13:05:59',
                'updated_at' => '2025-07-25 13:05:59',
                'deleted_at' => NULL,
            ),
            15 => 
            array (
                'id' => 16,
                'creator_id' => 1,
                'category_id' => 2,
                'image' => 'YpDj3JCiGFiGYwO3KaSnSWvrDlICg0oT6QMlXN1o.webp',
                'slug' => 'macbook-air-13-inch-m2-chip',
            'title' => 'MacBook Air (13-inch) M2 chip',
                'description' => 'Midnight, 16GB, 256GB',
                'price' => '1999.00',
                'created_at' => '2025-07-25 13:07:13',
                'updated_at' => '2025-07-25 13:07:13',
                'deleted_at' => NULL,
            ),
            16 => 
            array (
                'id' => 17,
                'creator_id' => 1,
                'category_id' => 2,
                'image' => 'rwIOoQ3YX1m3Ktx1NgDyDFYDofJF946LbbCNFVI4.webp',
                'slug' => 'macbook-air-13-inch-m1-chip',
            'title' => 'MacBook Air (13-inch) M1 chip',
                'description' => 'Space Grey, 8GB, 256GB',
                'price' => '1649.00',
                'created_at' => '2025-07-25 13:08:05',
                'updated_at' => '2025-07-25 13:08:05',
                'deleted_at' => NULL,
            ),
            17 => 
            array (
                'id' => 18,
                'creator_id' => 1,
                'category_id' => 3,
                'image' => 'Yc14E7NeTNixbeaiwmHZFMF6MumOrT5WFQZ2HX6F.webp',
                'slug' => 'macbook-pro-16-inch-m4-max',
            'title' => 'MacBook Pro (16-inch) M4 Max',
                'description' => 'Silver, 36GB, 1TB',
                'price' => '8269.00',
                'created_at' => '2025-07-25 13:10:18',
                'updated_at' => '2025-07-25 13:10:18',
                'deleted_at' => NULL,
            ),
            18 => 
            array (
                'id' => 19,
                'creator_id' => 1,
                'category_id' => 3,
                'image' => '3UXHNHhfgyeesuBDMKDZIPOxoSS19pyCSKv60Jyz.webp',
                'slug' => 'macbook-pro-16-inch-m4-pro',
            'title' => 'MacBook Pro (16-inch) M4 Pro',
                'description' => 'Silver, 48GB, 512GB',
                'price' => '6799.00',
                'created_at' => '2025-07-25 13:11:21',
                'updated_at' => '2025-07-25 13:11:21',
                'deleted_at' => NULL,
            ),
            19 => 
            array (
                'id' => 20,
                'creator_id' => 1,
                'category_id' => 3,
                'image' => 'DJwmp4JE7hXT5155LXaXT1x1LOrCmTWxbxbyCYwy.webp',
                'slug' => 'macbook-pro-14-inch-m4-max',
            'title' => 'MacBook Pro (14-inch) M4 Max',
                'description' => 'Silver, 36GB, 1TB',
                'price' => '7699.00',
                'created_at' => '2025-07-25 13:12:47',
                'updated_at' => '2025-07-25 13:12:47',
                'deleted_at' => NULL,
            ),
            20 => 
            array (
                'id' => 21,
                'creator_id' => 1,
                'category_id' => 3,
                'image' => 'EuBeLdLNhblv8T9dfviEOrGTJJ6tm2lTSxEbVmrU.webp',
                'slug' => 'macbook-pro-14-inch-m4-pro',
            'title' => 'MacBook Pro (14-inch) M4 Pro',
                'description' => 'Silver, 24GB, 512GB',
                'price' => '4899.00',
                'created_at' => '2025-07-25 13:13:40',
                'updated_at' => '2025-07-25 13:13:40',
                'deleted_at' => NULL,
            ),
            21 => 
            array (
                'id' => 22,
                'creator_id' => 1,
                'category_id' => 3,
                'image' => 'gSEGkreY4mBt0P6jEkqugkXw0JUtNAUxcmIp3umK.webp',
                'slug' => 'macbook-pro-14-inch-m4-chip',
            'title' => 'MacBook Pro (14-inch) M4 chip',
                'description' => 'Silver, 24GB, 1TB',
                'price' => '4749.00',
                'created_at' => '2025-07-25 13:14:51',
                'updated_at' => '2025-07-25 13:14:51',
                'deleted_at' => NULL,
            ),
            22 => 
            array (
                'id' => 23,
                'creator_id' => 1,
                'category_id' => 3,
                'image' => 'oPQTNtcWQeoyZyZzorhudOuK7o5Txa78O4Czpbo5.webp',
                'slug' => 'macbook-pro-14-inch-m1-pro',
            'title' => 'MacBook Pro (14-inch) M1 Pro',
                'description' => 'Space Grey, 64GB, 1TB',
                'price' => '8294.00',
                'created_at' => '2025-07-25 13:15:41',
                'updated_at' => '2025-07-25 13:15:41',
                'deleted_at' => NULL,
            ),
            23 => 
            array (
                'id' => 24,
                'creator_id' => 1,
                'category_id' => 4,
                'image' => 'FDBjpdyUjz4vTqjiRrmVvhuzdra048vAO6ch3Qv5.webp',
                'slug' => 'imac-24-inch-m4-chip',
            'title' => 'iMac (24-inch) M4 chip',
                'description' => 'Blue, 16GB, 256GB',
                'price' => '3499.00',
                'created_at' => '2025-07-25 13:17:05',
                'updated_at' => '2025-07-25 13:17:05',
                'deleted_at' => NULL,
            ),
            24 => 
            array (
                'id' => 25,
                'creator_id' => 1,
                'category_id' => 4,
                'image' => 'FatoAo9gRdLLgssaUJ7pxOePYnTG70NYg2l8H4Gp.webp',
                'slug' => 'imac-24-inch-m1-chip',
            'title' => 'iMac (24-inch) M1 chip',
                'description' => 'Pink, 8GB, 512GB',
                'price' => '3299.00',
                'created_at' => '2025-07-25 13:18:07',
                'updated_at' => '2025-07-25 13:18:07',
                'deleted_at' => NULL,
            ),
            25 => 
            array (
                'id' => 26,
                'creator_id' => 1,
                'category_id' => 5,
                'image' => 'BQKaieJoR4t7jOvxroXMGHJkwtpna0RYdevpeBlN.webp',
                'slug' => 'mac-mini-m4-pro',
                'title' => 'Mac mini M4 Pro',
                'description' => 'Silver, 24GB, 512GB',
                'price' => '3299.00',
                'created_at' => '2025-07-25 13:19:30',
                'updated_at' => '2025-07-25 13:19:30',
                'deleted_at' => NULL,
            ),
            26 => 
            array (
                'id' => 27,
                'creator_id' => 1,
                'category_id' => 5,
                'image' => 'q1631fAtaOToMxB6NC60vkuSclhzkw3D8ppL7nUO.webp',
                'slug' => 'mac-mini-m4',
                'title' => 'Mac mini M4',
                'description' => 'Silver, 16GB, 256GB',
                'price' => '1439.99',
                'created_at' => '2025-07-25 13:20:31',
                'updated_at' => '2025-07-25 13:20:31',
                'deleted_at' => NULL,
            ),
            27 => 
            array (
                'id' => 28,
                'creator_id' => 1,
                'category_id' => 5,
                'image' => '54u3v3G8tDtZrOeIrJRCrHsPCOOml8eykgB2Dk5U.webp',
                'slug' => 'mac-mini-m2',
                'title' => 'Mac mini M2',
                'description' => 'Silver, 8GB, 512GB',
                'price' => '1939.00',
                'created_at' => '2025-07-25 13:21:19',
                'updated_at' => '2025-07-25 13:21:19',
                'deleted_at' => NULL,
            ),
            28 => 
            array (
                'id' => 29,
                'creator_id' => 1,
                'category_id' => 6,
                'image' => 'KkhzoH1ZcNgW2gYodyBGvTWgzqRaPAaWfTo2mrXu.webp',
                'slug' => 'apple-watch-series-10-sport-band',
                'title' => 'Apple Watch Series 10 Sport Band',
                'description' => 'Jet Black',
                'price' => '1149.00',
                'created_at' => '2025-07-25 13:27:00',
                'updated_at' => '2025-07-25 13:27:00',
                'deleted_at' => NULL,
            ),
            29 => 
            array (
                'id' => 30,
                'creator_id' => 1,
                'category_id' => 6,
                'image' => 'EJ2fzcmii7ipKVGlJLFXInN9bYm1ODDbWQ0THQL5.webp',
                'slug' => '2024-apple-watch-se-sport-band',
                'title' => '2024 Apple Watch SE Sport Band',
                'description' => 'Midnight',
                'price' => '469.99',
                'created_at' => '2025-07-25 13:27:43',
                'updated_at' => '2025-07-25 13:27:43',
                'deleted_at' => NULL,
            ),
            30 => 
            array (
                'id' => 31,
                'creator_id' => 1,
                'category_id' => 6,
                'image' => 'tVaAHvgJLdpn2eB3fpCVAqYpqZN8AC05YZA3vZ2g.webp',
                'slug' => '2024-apple-watch-ultra-2-ocean-band',
                'title' => '2024 Apple Watch Ultra 2 Ocean Band',
                'description' => 'Black',
                'price' => '1719.00',
                'created_at' => '2025-07-25 13:28:10',
                'updated_at' => '2025-07-25 13:28:10',
                'deleted_at' => NULL,
            ),
            31 => 
            array (
                'id' => 32,
                'creator_id' => 1,
                'category_id' => 6,
                'image' => 'tpNKfESQCwITLv6tBZ7l1mcdKGFJKJufTm4khveb.webp',
                'slug' => 'apple-watch-series-9-sport-loop',
                'title' => 'Apple Watch Series 9 Sport Loop',
                'description' => 'Midnight',
                'price' => '739.99',
                'created_at' => '2025-07-25 13:28:47',
                'updated_at' => '2025-07-25 13:28:47',
                'deleted_at' => NULL,
            ),
            32 => 
            array (
                'id' => 33,
                'creator_id' => 1,
                'category_id' => 6,
                'image' => 'eYt3DIMrDCAWduKE3FTdnfFJY1L4fFfjgh3i4JBp.webp',
                'slug' => 'apple-watch-series-8',
                'title' => 'Apple Watch Series 8',
                'description' => 'Silver',
                'price' => '1099.01',
                'created_at' => '2025-07-25 13:29:18',
                'updated_at' => '2025-07-25 13:29:18',
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}